"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING
import numpy as np
from magicgui.widgets import Container, FloatSlider, CheckBox, PushButton
from magicgui import magic_factory
from napari.types import ImageData
from scipy.ndimage import gaussian_filter

if TYPE_CHECKING:
    import napari


class BlurWidget(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()

        self.viewer = viewer

        # Widget pour choisir la couche image dans napari
        self.image_layer = magic_factory(annotation="napari.layers.Image")()

        # Slider pour le paramètre sigma du flou
        self.sigma_slider = FloatSlider(
            value=1.0, min=0.0, max=10.0, step=0.1, label="Flou sigma"
        )

        # Checkbox pour activer/désactiver l'application du flou
        self.apply_blur = CheckBox(text="Appliquer le flou", value=True)

        # Bouton pour réinitialiser sigma à 1.0
        self.reset_button = PushButton(text="Réinitialiser sigma")

        # Ajouter tous les widgets au container
        self.extend([self.image_layer, self.sigma_slider, self.apply_blur, self.reset_button])

        # Connecter les événements des widgets aux fonctions
        self.sigma_slider.changed.connect(self._update_image)
        self.apply_blur.changed.connect(self._update_image)
        self.image_layer.changed.connect(self._update_image)
        self.reset_button.changed.connect(self._reset_sigma)

    def _reset_sigma(self):
        self.sigma_slider.value = 1.0

    def _update_image(self):
        img_layer = self.image_layer.value
        if img_layer is None:
            return

        img = np.array(img_layer.data)

        if self.apply_blur.value:
            sigma = self.sigma_slider.value
            img = gaussian_filter(img, sigma=sigma)

        name = img_layer.name + "_flou"
        if name in self.viewer.layers:
            self.viewer.layers[name].data = img
        else:
            self.viewer.add_image(img, name=name)
